vk_domains:
  - id: public.bashkorttelenketherleyek
    name: "Bashkort telen kaderleyek!"
    language: ba
  - id: irta_tv
    name: "Good morning, REPUBLIC!| GTRK Bashkortostan"
    language: ba
  - id: club1135692
    name: "KURAY"
    language: ba
  - id: club.murtazarahimov
    name: "Country elder Murtaza Rakhimov"
    language: ba
  - id: vkbashkort
    name: "Bashkir projects | Bashkort projecttary"
    language: ba
  - id: club43514188
    name: "Yanybay Khammatov"
    language: ba
  - id: club1673691
    name: "Kurgan Bashkirs"
    language: ba
  - id: ataysalgazeta
    name: "Ataysal regional newspaper"
    language: ba
  - id: kiskeufa
    name: "Kiske Ufa newspaper"
    language: ba
  - id: club57785596
    name: "Loving season"
    language: ba
  - id: club160399987
    name: "Hanek magazine"
    language: ba
  - id: gumer_ber
    name: "My life is one"
    language: ba
  - id: bashkizi
    name: "Bashkortostan girl"
    language: ba
  - id: agidel_rb
    name: "Agidel magazine"
    language: ba
  - id: club192878295
    name: "Stories"
    language: ba
  - id: bashkortvk
    name: "USEFUL TIPS"
    language: ba
  - id: baishivo
    name: "Bashkirs"
    language: ba
  - id: xaram_rizik
    name: "Harmful and forbidden foods"
    language: ba
  - id: asaba_bashkorttar
    name: "TRUE BASHKIRS"
    language: ba
  - id: bashbst
    name: "BASHKIRS-BST"
    language: ba
  - id: arzakly_bash
    name: "Respected Bashkirs"
    language: ba
  - id: bashkorttarnoktaru
    name: "Bashkirs.RU"
    language: ba
  - id: amanatrb
    name: "Amanat children-youth magazine"
    language: ba
  - id: noktaru
    name: "Nokta.Ru KVN team"
    language: ba
  - id: club155279614
    name: "BASHKIRS"
    language: ba
  - id: club86891863
    name: "BASHKIRS"
    language: ba